### ISSUE TITLE
Unfired Crucible

### ISSUE THREAD

**Issue by dummy22328** [DucksTeam/Exnihilo_Bedrock#1]
So I made a comment about this on mcpedl but I figured it would be faster this way and so I made a custom skyfactory using a void template world I added your AddOn at the top of the addons list with vatonage advanced machinery and sypderrocks more gear and more tools mod with ikorbons mo creatures and ore generators and crops generators and cancercraft so I can have paxels buuut all the stuff in ur 1.05 update don't work and I downloaded 1.05 so I'm just a lil confused why it ain't working and since u probably know more then me about addons ima ask u if u could help me fix this that would be great

**Comment by NguyenDuck** [comment]
Can you send me your map?
I think that's a lot faster as you say and I'm pretty confused.

**Comment by dummy22328** [comment]
My game  was acting weird I had to Download the addon like 4 times until  it worked and I had made sure that I was on the right version so it's probably not ur fault it's probably just cause I run Minecraft on the worlds crappiest laptop

**Comment by NguyenDuck** [comment]
Looks like you solved the problem.
